language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: TH/0rZcre20ehUsc+m0nVMYrWrYMefjWUEyhlVR+OoXpPZUr9ZHCZ+7dFXozySeLH8JNJJEsvvDuc/ZMgTuQIiiTcpIjQlgR5mrEo+POe1LGpWAQDTsc99/1R/VkHj1QZFocUpx0rqVaWIcuh7KFTI5FGNobUrfMY0WRQsrbv8A=
    - secure: P4+VIEHymk5dGEzWeHRnWI14ajFmxY3BHIahDhaBG1uCBQbL0QN1z48iQwsk9hsR5n8eqt4rNg8wGq6+lnAyDEnPhxyHj+a4XS20PDMc0T8VN0csBKjgB2lnKnWAVswRxUdc3w3DDmxR4Gesl79Du8KCUU6uCWT8gOXXHl7IcXs=
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g protractor
install:
  - npm install
script:
  - grunt test:development
  - grunt test
  - grunt e2e --ci
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
addons:
  sauce_connect: true
